# My TMUX Config -- Install tpm first
# Run Prefix + (Shift + I) from a tmux session to reload 
set -g default-terminal "tmux-256color"
set -as terminal-features ',*:RGB'
set -gq utf8 on
set -g status-interval 5
set -g mouse on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'Nybkox/tmux-lazygit'


set -g @continuum-restore 'on'
set -g set-clipboard on

set -g @sidebar-tree-command 'eza --tree --icons=always --color=always --level=3 --git-ignore -I "__pycache__|node_modules|.git"'
set -g @sidebar-tree-pager 'less -RS'

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'slanted'
set -g @catppuccin_window_text         ' #W'
set -g @catppuccin_window_current_text ' #W'
set -g @catppuccin_window_flags        'icon'

set -g  '@catppuccin_load_icon' '󰍛 '
set -gF '@catppuccin_load_color' '#{E:@thm_yellow}'
set -g  '@catppuccin_load_text' '#(/home/kk/.tmux/scripts/load.sh)'

run '~/.tmux/plugins/tpm/tpm'

set -gF '@catppuccin_status_load_icon_bg' '#{E:@thm_yellow}'
%hidden MODULE_NAME="load"
source '/home/kk/.tmux/plugins/tmux/utils/status_module.conf'

set -g status 2
set -g status-left ""
set -g status-right-length 200
set -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_load}#{E:@catppuccin_status_session}#{E:@catppuccin_status_host}#{E:@catppuccin_status_date_time}"

set -g status-justify left

set -g status-format[1] "#[list=on align=#{status-justify}]#[list=left-marker]<#[list=right-marker]>#[list=on]#{W:#[range=window|#{window_index} #{window-status-style}#{?#{&&:#{window_last_flag},#{!=:#{window-status-last-style},default}}, #{window-status-last-style},}#{?#{&&:#{window_bell_flag},#{!=:#{window-status-bell-style},default}}, #{window-status-bell-style},#{?#{&&:#{||:#{window_activity_flag},#{window_silence_flag}},#{!=:#{window-status-activity-style},default}}, #{window-status-activity-style},}}]#[push-default]#{T:window-status-format}#[pop-default]#[norange default]#{?window_end_flag,,#{window-status-separator}},#[range=window|#{window_index} list=focus #{?#{!=:#{window-status-current-style},default},#{window-status-current-style},#{window-status-style}}#{?#{&&:#{window_last_flag},#{!=:#{window-status-last-style},default}}, #{window-status-last-style},}#{?#{&&:#{window_bell_flag},#{!=:#{window-status-bell-style},default}}, #{window-status-bell-style},#{?#{&&:#{||:#{window_activity_flag},#{window_silence_flag}},#{!=:#{window-status-activity-style},default}}, #{window-status-activity-style},}}]#[push-default]#{T:window-status-current-format}#[pop-default]#[norange list=on default]#{?window_end_flag,,#{window-status-separator}}}"

set -g status-format[0] "#[align=right range=right #{status-right-style}]#[push-default]#{T;=/#{status-right-length}:status-right}#[pop-default]#[norange default]"
